on:
 workflow_dispatch:

jobs:
  first_job:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello from Git hub" | ls -al
      - run: |
         for item in dummy-handler
         do
            zip -r $item.zip apps/$item/main.py
         done
      - uses: actions/upload-artifact@v4
        with:
          name: zip-file
          path: ./dummy-handler.zip
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::236934871277:role/cicd-pipeline
          aws-region: ap-south-1
      - run: aws s3 ls
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
        working-directory: infra
      - run: terraform plan -out=tfplan
        working-directory: infra
      - uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ./infra/tfplan
  apply_job:
    needs: first_job
    environment: production
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
       - uses: actions/checkout@v4
       - uses: aws-actions/configure-aws-credentials@v4
         with:
          role-to-assume: arn:aws:iam::236934871277:role/cicd-pipeline
          aws-region: ap-south-1
       - uses: actions/download-artifact@v4
         with:
           name: tfplan
           path: infra
       - uses: hashicorp/setup-terraform@v3
       - run: terraform init
         working-directory: infra
       - run: terraform apply "tfplan"
         working-directory: infra
    
